#eww
name: Install coreutils-dev

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the 'main' branch

jobs:
  install:
    runs-on: ubuntu-22.04  # Use an Ubuntu runner for the job
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout the code

    - name: install deps and make
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential 
        bash install.sh
        strip advcp
        strip advmv
        
        
    - name: Upload advcpmv release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          advcp
          advmv
